"""empty message

Revision ID: 084b3ec32aea
Revises: df4c95c62606
Create Date: 2020-06-11 20:01:10.653026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '084b3ec32aea'
down_revision = 'df4c95c62606'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'past_shows')
    op.drop_column('Venue', 'upcoming_shows')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('upcoming_shows', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('Venue', sa.Column('past_shows', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
