"""empty message

Revision ID: 69029d7f8ce3
Revises: 084b3ec32aea
Create Date: 2020-06-11 20:01:58.050591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69029d7f8ce3'
down_revision = '084b3ec32aea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('past_shows', sa.ARRAY(sa.Integer()), nullable=True, foreign_keys='Artist.id'))
    op.add_column('Venue', sa.Column('upcoming_shows', sa.ARRAY(sa.Integer()), nullable=True, foreign_keys='Artist.id'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'upcoming_shows')
    op.drop_column('Venue', 'past_shows')
    # ### end Alembic commands ###
