"""empty message

Revision ID: 73e5c42ead95
Revises: 431d852acf74
Create Date: 2020-06-11 20:14:46.958594

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '73e5c42ead95'
down_revision = '431d852acf74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'past_shows')
    op.drop_column('Venue', 'upcoming_shows')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('upcoming_shows', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True))
    op.add_column('Venue', sa.Column('past_shows', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
