"""empty message

Revision ID: 76dcbe697fd9
Revises: 7d37ffa17713
Create Date: 2020-06-03 00:01:35.073295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76dcbe697fd9'
down_revision = '7d37ffa17713'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Venue_past_shows_fkey', 'Venue', type_='foreignkey')
    op.drop_constraint('Venue_upcoming_shows_fkey', 'Venue', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('Venue_upcoming_shows_fkey', 'Venue', 'Artist', ['upcoming_shows'], ['id'])
    op.create_foreign_key('Venue_past_shows_fkey', 'Venue', 'Artist', ['past_shows'], ['id'])
    # ### end Alembic commands ###
