"""empty message

Revision ID: 80f5dbac65d3
Revises: 56f86b550c9b
Create Date: 2020-06-12 23:00:02.325334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80f5dbac65d3'
down_revision = '56f86b550c9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('past_shows', sa.ARRAY(sa.Integer()), nullable=True, foreign_keys='Show.id'))
    op.add_column('Artist', sa.Column('seeking_description', sa.String(), nullable=True))
    op.add_column('Artist', sa.Column('upcoming_shows', sa.ARRAY(sa.Integer()), nullable=True, foreign_keys='Show.id'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'upcoming_shows')
    op.drop_column('Artist', 'seeking_description')
    op.drop_column('Artist', 'past_shows')
    # ### end Alembic commands ###
