"""empty message

Revision ID: c30a3dd0b72b
Revises: 73e5c42ead95
Create Date: 2020-06-11 20:15:12.503165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c30a3dd0b72b'
down_revision = '73e5c42ead95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('past_shows', sa.ARRAY(sa.Integer()), nullable=True, foreign_keys='Show.id'))
    op.add_column('Venue', sa.Column('upcoming_shows', sa.ARRAY(sa.Integer()), nullable=True, foreign_keys='Show.id'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'upcoming_shows')
    op.drop_column('Venue', 'past_shows')
    # ### end Alembic commands ###
