"""empty message

Revision ID: df4c95c62606
Revises: 0a83cedb2bcc
Create Date: 2020-06-05 11:09:56.016144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df4c95c62606'
down_revision = '0a83cedb2bcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('upcoming', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Show', 'upcoming')
    # ### end Alembic commands ###
