name: Auto Assign Reviewers

on:
  pull_request:
    types: [opened, synchronize,reopened]

jobs:
  assign-reviewers:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Check base branch and assign reviewers
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const baseBranch = context.payload.pull_request.base.ref;

            let reviewers = [];
            if (baseBranch === "master") {
              reviewers = "anilbtg_ALL"; // Replace with actual GitHub usernames
            } else {
              reviewers = "anilbtg_onlyone"; // Different reviewers for other branches
            }

            if (reviewers.length > 0) {
              github.rest.pulls.requestReviewers({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.payload.pull_request.number,
                team_reviewers: [reviewers]
              });
            }
